ALTER TABLE `owned_vehicles`
ADD COLUMN `metadata` LONGTEXT DEFAULT NULL,
ADD COLUMN `mileage` INT(11) DEFAULT 0,
ADD COLUMN `coords` LONGTEXT DEFAULT NULL,
ADD COLUMN `keys` LONGTEXT DEFAULT '[]',
ADD COLUMN `lastparking` VARCHAR(100) DEFAULT NULL;
